### ISSUE TITLE
Ratchet & Clank 2, 3 - UI glitches

### ISSUE THREAD

**Issue by Electry** [Electry/VitaGrafix#121]
Changing the resolution in R&C 2 and 3 causes some of the UI elements to get clipped.

![](https://user-images.githubusercontent.com/12598379/45221532-00ac1300-b2b2-11e8-8ca7-ca2f1ba6a54f.png)

**Comment by Electry** [comment]
An attempt to fix the UI issues in R&C 2

```
[PCSF00485,eboot.bin]
[PCSF00482,rc2.self,0x7a1d621c]
[PCSA00133,rc2.self,0x7a1d621c]
@FB
0:0x19054 t2_mov(1,14,0xC00000)
0:0x1D62 t2_mov(1,0,<fb_w>)
0:0x1D66 t2_mov(1,1,<fb_h>)
0:0xA56540 t1_movt(1,<r,<to_fl,<fb_h>>,16>)
0:0xA564E8 t1_movt(1,<r,<to_fl,</,<*,<fb_w>,88>,720>>,16>)
0:0xA564A2 t3_mov(4,<to_fl,</,<*,<fb_w>,544>,720>>)
0:0xA564A6 t1_movt(4,<r,<to_fl,</,<*,<fb_w>,544>,720>>,16>)
0:0xA564AE nop() *3
```

**Comment by Electry** [comment]
fixed

**Comment by ProxyFenix** [comment]
I guess this hasn't been merged into the code, so how do you get the patch to work? (First time user)

**Comment by Electry** [comment]
what do you mean? It has been fixed in patchlist.txt

Installation instructions are in
https://github.com/Electry/VitaGrafix/wiki/Installation
https://github.com/Electry/VitaGrafixPatchlist#installation

**Comment by ProxyFenix** [comment]
Yeah, found it
It didn't fix it tho, I'm at 5.0.2 and the hud is malfunctioning like in the pic above. Those the code in the patchlist means that it only works on 720p?

**Comment by ProxyFenix** [comment]
Nevermind, fixed it
Thanks for the help!

**Comment by Electry** [comment]
np, glad you got it working :)
